---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datalake-boat
spec:
  type: service
  lifecycle: production
  owner: guests
  providesApis: [datalake-boat-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: datalake-boat-api
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    paths:
      /truncate:
        delete:
          summary: Empty the lake
          responses:
            "200":
              description: All gone!